// Package contribution implements all phases (initialization, contribution, verification)
// of a multi-party computation setup ceremony.
package contribution

import (
	"io"

	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/backend/groth16/bn254/mpcsetup"
	cs "github.com/consensys/gnark/constraint/bn254"
)

type contribution struct {
	contribution *mpcsetup.Phase2
	srsCommons   *mpcsetup.SrsCommons
	evals        *mpcsetup.Phase2Evaluations
	beacon       []byte
	count        int
}

// Verifiable is an interface for a contribution object that is going to be verified by a verifier.
type Verifiable interface {
	ReadFrom(reader io.Reader) (int64, error)
}

// Contributable is an interface for a contribution object that is going to be contributed to.
type Contributable interface {
	Contribute()
	ReadFrom(reader io.Reader) (int64, error)
	WriteTo(writer io.Writer) (int64, error)
}

// NewContributable returns a new empty contribution instance implementing Contributable.
func NewContributable() Contributable {
	return &contribution{contribution: new(mpcsetup.Phase2)}
}

// Contribute contributes randomness to contribution.
func (p *contribution) Contribute() {
	p.contribution.Contribute()
}

// ReadFrom reads the contribution from the reader.
//
// It returns the number of bytes read and any error encountered.
func (p *contribution) ReadFrom(reader io.Reader) (int64, error) {
	return p.contribution.ReadFrom(reader)
}

// WriteTo writes the contribution object to the writer.
//
// It returns the number of bytes written and any error encountered.
func (p *contribution) WriteTo(writer io.Writer) (int64, error) {
	return p.contribution.WriteTo(writer)
}

// Contribution is an interface for doing operations on a contribution from the ceremony coordinator perspective.
type Contribution interface {
	NewVerifiable() Verifiable
	AddContribution(next Verifiable) error
	ExtractKeys() (groth16.ProvingKey, groth16.VerifyingKey)
	WriteTo(writer io.Writer) (int64, error)
	GetCount() int
}

// New creates a new Contribution from a Phase 1 object, R1CS and beacon.
//
// phase1 is the Phase 1 object produced either by Gnark of by the `ptau` command from a Snarkjs file.
// r1cs is the R1CS constraint system object generated by Gnark for a circuit the ceremony is performed for.
// beacon is a 32-byte array of random bytes. It is used for generating Phase 1 and later for keys generation.
func New(phase1 *mpcsetup.Phase1, r1cs *cs.R1CS, beacon []byte) Contribution {
	p2 := new(mpcsetup.Phase2)
	srsCommons := phase1.Seal(beacon)
	evals := p2.Initialize(r1cs, &srsCommons)

	return &contribution{
		p2,
		&srsCommons,
		&evals,
		beacon,
		0,
	}
}

// NewVerifiable returns a new empty contribution instance implementing Verifiable.
//
// This object can be reconstructed from a stream of bytes with ReadFrom and passed to AddContribution for verification.
func (p *contribution) NewVerifiable() Verifiable {
	return &contribution{contribution: new(mpcsetup.Phase2)}
}

// AddContribution adds a new contribution to the existing one.
//
// The next object is verified against the current one. If verification fails, an error is returned.
// If the contribution is valid, next considered the new state.
func (p *contribution) AddContribution(next Verifiable) error {
	err := p.contribution.Verify(next.(*contribution).contribution)
	if err != nil {
		return err
	}
	p.contribution = next.(*contribution).contribution
	p.count++
	return nil
}

// ExtractKeys extracts the proving and verifying keys from the contribution.
func (p *contribution) ExtractKeys() (groth16.ProvingKey, groth16.VerifyingKey) {
	// We intentionally don't use mpcsetup.VerifyPhase2() here.
	//
	// mpcsetup.VerifyPhase2() accepts a list of all accepted contributions and runs
	// them in pairs through .Verify(). Then, the last contribution of this chain
	// is used to call .Seal() to get the keys.
	//
	// This is exactly what has been already done in p.AddContribution() for every incoming
	// contribution. Our p.contribution is the result of .Verify() passing
	// for every submitted contribution. It is enough to implement only the last step
	// of mpcsetup.VerifyPhase2(), which is .Seal().
	return p.contribution.Seal(p.srsCommons, p.evals, p.beacon)
}

// GetCount returns the number of contributions added to the contribution.
func (p *contribution) GetCount() int {
	return p.count
}
