// Package phase2 implements functions interacting with multi-party computation Phase 2 objects produced by Gnark.
package phase2

import (
	"io"

	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/backend/groth16/bn254/mpcsetup"
	cs "github.com/consensys/gnark/constraint/bn254"
)

type phase2 struct {
	contribution *mpcsetup.Phase2
	srsCommons   *mpcsetup.SrsCommons
	r1cs         *cs.R1CS
	beacon       []byte
}

// Verifiable is an interface for a Phase 2 object that is going to be verified by the coordinator.
type Verifiable interface {
	GetContribution() interface{}
	ReadFrom(reader io.Reader) (int64, error)
}

// Contributor is an interface for a Phase 2 object that is going to be contributed to by a contributor.
type Contributor interface {
	Contribute()
	ReadFrom(reader io.Reader) (int64, error)
	WriteTo(writer io.Writer) (int64, error)
}

// NewContributor returns a new empty Phase 2 instance implementing Contributor.
func NewContributor() Contributor {
	return &phase2{contribution: &mpcsetup.Phase2{}}
}

// Contribute contributes randomness to the Phase 2 object.
func (p *phase2) Contribute() {
	p.contribution.Contribute()
}

// ReadFrom reads the Phase 2 object from the reader.
//
// It returns the number of bytes read and any error encountered.
func (p *phase2) ReadFrom(reader io.Reader) (int64, error) {
	p.contribution = new(mpcsetup.Phase2)
	return p.contribution.ReadFrom(reader)
}

// WriteTo writes the Phase 2 object to the writer.
//
// It returns the number of bytes written and any error encountered.
func (p *phase2) WriteTo(writer io.Writer) (int64, error) {
	return p.contribution.WriteTo(writer)
}

// Coordinator is an interface for doing operations on a Phase 2 object from the ceremony coordinator perspective.
type Coordinator interface {
	NewVerifiable() Verifiable
	AddContribution(next Verifiable) error
	ExtractKeys() (groth16.ProvingKey, groth16.VerifyingKey)
	WriteTo(writer io.Writer) (int64, error)
}

// FromPhase1 creates a new Coordinator from a Phase 1 object, R1CS and beacon.
//
// phase1 is the Phase 1 object produced either by Gnark of by the `ptau` command from a Snarkjs file.
// r1cs is the R1CS constraint system object generated by Gnark for a circuit the ceremony is performed for.
// beacon is a 32-byte array of random bytes. It is used for generating Phase 1 and later for keys generation.
func FromPhase1(phase1 *mpcsetup.Phase1, r1cs *cs.R1CS, beacon []byte) Coordinator {
	p2 := new(mpcsetup.Phase2)
	srsCommons := phase1.Seal(beacon)
	_ = p2.Initialize(r1cs, &srsCommons)

	return &phase2{
		p2,
		&srsCommons,
		r1cs,
		beacon,
	}
}

// NewVerifiable returns a new empty Phase 2 instance implementing Verifiable.
//
// This object can be reconstructed from a stream of bytes with ReadFrom and passed to AddContribution for verification.
func (p *phase2) NewVerifiable() Verifiable {
	return &phase2{contribution: &mpcsetup.Phase2{}}
}

// AddContribution adds a contribution to the Phase 2 object.
//
// The next object is verified against the current one. If verification fails, an error is returned.
// If the contribution is valid, next considered the new Phase 2 state.
func (p *phase2) AddContribution(next Verifiable) error {
	contributionBody := next.GetContribution().(*mpcsetup.Phase2)
	err := p.contribution.Verify(contributionBody)
	if err != nil {
		return err
	}
	p.contribution = contributionBody
	return nil
}

// ExtractKeys extracts the proving and verifying keys from the Phase 2 object.
func (p *phase2) ExtractKeys() (groth16.ProvingKey, groth16.VerifyingKey) {
	// We intentionally don't use mpcsetup.VerifyPhase2() here.
	//
	// mpcsetup.VerifyPhase2() accepts a list of all accepted contributions and runs
	// them in pairs through .Verify(). Then, the last contribution of this chain
	// is used to call .Seal() to get the keys.
	//
	// This is exactly what has been already done in p.AddContribution() for every incoming
	// contribution. Our p.contribution is the result of .Verify() passing
	// for every submitted contribution. It is enough to implement only the last step
	// of mpcsetup.VerifyPhase2(), which is .Seal().
	evals := new(mpcsetup.Phase2).Initialize(p.r1cs, p.srsCommons)
	return p.contribution.Seal(p.srsCommons, &evals, p.beacon)
}

// GetContribution returns the underlying contribution of the Phase 2 object.
func (p *phase2) GetContribution() interface{} {
	return p.contribution
}
